#!/usr/bin/env node
/**
 * scripts/gen-component-catalog.ts
 *
 * Generates docs/component-catalog.md from the single source of truth:
 * src/content/gallery.ts (the galleryManifest array).
 *
 * Implementation strategy — why we use --experimental-strip-types:
 *   gallery.ts is a real TypeScript file that we own. Since Node >=22 supports
 *   --experimental-strip-types, we can import it directly without a build step
 *   or a regex hack. No jiti, no tsx, no esbuild dependency needed.
 *   The script file is itself TypeScript, so both ends of the import chain are
 *   typed and the drift test can import generateCatalog() with full type safety.
 *
 * Usage:
 *   npm run gen:catalog           — regenerate docs/component-catalog.md
 *   node --experimental-strip-types scripts/gen-component-catalog.ts
 *
 * The Vitest test (src/tests/component-catalog-drift.test.ts) imports
 * generateCatalog() directly and diffs its output against the committed file,
 * failing CI when drift is detected.
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import process from 'node:process';
import type { GalleryEntry } from '../src/content/gallery.ts';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const repoRoot = join(__dirname, '..');

/** Import the gallery manifest lazily so the drift test doesn't trigger I/O at module load. */
async function loadManifest(): Promise<{
  manifest: GalleryEntry[];
  categoryLabels: Record<GalleryEntry['category'], string>;
  categoryOrder: GalleryEntry['category'][];
}> {
  const mod = await import('../src/content/gallery.ts');
  return {
    manifest: mod.galleryManifest,
    categoryLabels: mod.categoryLabels,
    categoryOrder: mod.categoryOrder,
  };
}

function statusIcon(s: GalleryEntry['status']): string {
  if (s === 'stable') return '✅';
  if (s === 'beta') return '🔵';
  return '🧪';
}

/**
 * Pure function: generates the full catalog markdown string.
 * Exported so the drift test can call it without touching the filesystem.
 */
export async function generateCatalog(): Promise<string> {
  const { manifest, categoryLabels, categoryOrder } = await loadManifest();

  // Group entries by category in the canonical order.
  const byCategory = new Map<GalleryEntry['category'], GalleryEntry[]>();
  for (const cat of categoryOrder) {
    byCategory.set(cat, []);
  }
  for (const entry of manifest) {
    const bucket = byCategory.get(entry.category);
    if (bucket) {
      bucket.push(entry);
    } else {
      // Unknown future category — append at end rather than silently drop.
      byCategory.set(entry.category, [entry]);
    }
  }

  const lines: string[] = [];

  lines.push('<!-- AUTO-GENERATED by scripts/gen-component-catalog.ts — do not edit by hand. -->');
  lines.push('<!-- To update: npm run gen:catalog -->');
  lines.push('');
  lines.push('# Component catalog');
  lines.push('');
  lines.push(
    'Generated from [`src/content/gallery.ts`](../src/content/gallery.ts). ' +
      'Every entry here is rendered live at `/gallery`.',
  );
  lines.push('');
  lines.push(
    `**Total:** ${manifest.length} gallery entries across ${byCategory.size} categories.`,
  );
  lines.push('');
  lines.push('**Legend**');
  lines.push('');
  lines.push('- ✅ **stable** — ships today, shown in `/gallery`');
  lines.push('- 🔵 **beta** — functional but API may change');
  lines.push('- 🧪 **experimental** — proof-of-concept, expect breakage');
  lines.push('');
  lines.push('---');
  lines.push('');

  let sectionNum = 0;
  for (const [cat, entries] of byCategory) {
    if (entries.length === 0) continue;
    sectionNum++;
    const label = categoryLabels[cat] ?? cat;
    lines.push(`## ${sectionNum}. ${label}`);
    lines.push('');
    lines.push('| Component | Status | Summary | Source |');
    lines.push('|---|---|---|---|');
    for (const e of entries) {
      const icon = statusIcon(e.status);
      lines.push(
        `| **${e.name}** | ${icon} ${e.status} | ${e.summary} | [\`${e.source}\`](../${e.source}) |`,
      );
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push(
    '_Last generated: ' +
      new Date().toISOString().slice(0, 10) +
      '. Run `npm run gen:catalog` to refresh._',
  );
  lines.push('');

  return lines.join('\n');
}

// When run directly (not imported by the test), write the file.
const isMain = process.argv[1] === fileURLToPath(import.meta.url);
if (isMain) {
  const outPath = join(repoRoot, 'docs/component-catalog.md');
  const content = await generateCatalog();
  writeFileSync(outPath, content, 'utf-8');
  console.log(`gen:catalog: wrote ${outPath} (${content.length} chars)`);
}
